### ISSUE TITLE
Error installing in ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by WCEdison** [pele-python/pele#161]
hi, I had been using pele for a undergraduate project in 2017 on ubuntu OS, but I have encountered an error when I am reopening the project and installing the module on the latest system. 

since it's a newly installed system, I have used essential-build, update and upgrade to get the latest version of the library. 

The following is the log of the error, I have also tried switching the python version from 3.4 to 2.7, I wonder if there's any specific version of various libraries I need to get ?

easc0000@easc0000-System-Product-Name:~/Documents/pele-master$ python setup.py 
Cythonizing sources
Processing pele/utils/_pressure_tensor.pyx
cython --fast-fail --cplus -I /home/easc0000/Documents/pele-master/pele/potentials -v -X embedsignature=True -o _pressure_tensor.cxx _pressure_tensor.pyx
Compiling /home/easc0000/Documents/pele-master/pele/utils/_pressure_tensor.pyx
/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/easc0000/Documents/pele-master/pele/utils/_pressure_tensor.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: /home/easc0000/Documents/pele-master/pele/potentials/_pele.pxd:70:40: Buffer unpacking not optimized away.
warning: /home/easc0000/Documents/pele-master/pele/potentials/_pele.pxd:70:40: Buffer unpacking not optimized away.
warning: /home/easc0000/Documents/pele-master/pele/potentials/_pele.pxd:91:47: Buffer unpacking not optimized away.
warning: /home/easc0000/Documents/pele-master/pele/potentials/_pele.pxd:91:47: Buffer unpacking not optimized away.
warning: /home/easc0000/Documents/pele-master/pele/potentials/_pele.pxd:123:43: Buffer unpacking not optimized away.
warning: /home/easc0000/Documents/pele-master/pele/potentials/_pele.pxd:123:43: Buffer unpacking not optimized away.
Traceback (most recent call last):
  File "/home/easc0000/.local/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 788, in setuptools_main
    return main(command_line = 1)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 806, in main
    result = compile(sources, options)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_multiple(source, options)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 755, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 513, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 143, in process_implementation
    self.generate_c_code(env, options, result)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 379, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1983, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1745, in generate_function_body
    self.body.generate_execution_code(code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 448, in generate_execution_code
    stat.generate_execution_code(code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/UtilNodes.py", line 326, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 6909, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 448, in generate_execution_code
    stat.generate_execution_code(code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 5169, in generate_execution_code
    self.generate_assignment_code(code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 5466, in generate_assignment_code
    self.lhs.generate_assignment_code(self.rhs, code)
  File "/home/easc0000/.local/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 4105, in generate_assignment_code
    self.result() if self.lhs.is_pyobject else None,
AttributeError: 'IndexNode' object has no attribute 'lhs'
Traceback (most recent call last):
  File "/home/easc0000/Documents/pele-master/cythonize.py", line 200, in <module>
    main()
  File "/home/easc0000/Documents/pele-master/cythonize.py", line 197, in main
    find_process_files(root_dir)
  File "/home/easc0000/Documents/pele-master/cythonize.py", line 184, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "/home/easc0000/Documents/pele-master/cythonize.py", line 160, in process
    processor_function(fromfile, tofile)
  File "/home/easc0000/Documents/pele-master/cythonize.py", line 78, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    generate_cython()
  File "setup.py", line 71, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

**Comment by js850** [comment]
I don't think pele is being actively maintained anymore.  Most likely what happened that some package was updated and broke backwards compatibility which then causes errors in pele.  networkx does this frequently, but it looks like this error is due to cython.  You can try fixing the broken dependency, or use an older version of cython.  Please keep this thread updated if you find a solution.

**Comment by bkimo** [comment]
Ubuntu 18.04 made Python 3.6 or higher version as its default python. Pele must be installed with Python 2.x version. I installed Python 2.7.x and made a path to python2. Also, when installing cython, you better make sure you are using `pip` for python 2.x.In my case, I used `pip2`.  I followed 'Tutorial' in code information document. `Getting Started` section was OK. But, in the section `Creating Your Potential`, the last part  "finding transition state pathways"  produces an error: When trying to 'connect all minima to the lowest energy minimum', errors come "NotImplemetedError".  So, I tried `nosechecks` procedure, which generates more troubled errors and I am trying to figure out what those errors mean and how to fix it.

**Comment by smcantab** [comment]
main branch is not being actively maintained. A fork by @klicperajo has
been developed until very recently and it works fine on ubuntu 18. Soon
we'll send the PR and a number of issues will be fixed. @farrelljd has
started a PR to make pele compatible with python3, so I expect that soon
enough pele will also work with the default installation on more recent os.
I suggest you install anaconda python 2. Before the merge from @kliperajo
's fork happens, I'll see that I can create a pipfile to simplify the
installation process
